### ISSUE TITLE
Búsqueda y Filtro de productos

### ISSUE THREAD

**Issue by LeaTex** [LeaTex/unq-iisoft-2021c1-turest#30]
- [ ] Buscar producto por nombre #25 
- [ ] Filtrar por precios #26 
- [ ] Filtrar por perfil alimentario #27
