### ISSUE TITLE
Gestión del salón

### ISSUE THREAD

**Issue by LeaTex** [LeaTex/unq-iisoft-2021c1-turest#32]
- [x] Alta de mozo #10 
- [ ] Activar cantidad de mesas #11 
- [x] Asignar mesas a un mozo #13
