### ISSUE TITLE
Gestión del cliente

### ISSUE THREAD

**Issue by LeaTex** [LeaTex/unq-iisoft-2021c1-turest#33]
- [ ] Solicitar mesa #16 
- [ ] Hacer un pedido #15 
- [ ] Configurar perfil alimentario #23 
- [ ] Ver resumen del pedido #17
