### ISSUE TITLE
Gestión del mozo

### ISSUE THREAD

**Issue by LeaTex** [LeaTex/unq-iisoft-2021c1-turest#34]
- [ ] Ver mesas asignadas #14 
- [ ] Marcar pedido como entregado #18 
- [ ] Cerrar la mesa #21
